
services:
  database:
    container_name: mongodb_quizzcards
    image: snkhadim/quizzcards-database
    volumes:
      - mongo-data:/data/db
    networks:
      - quizzcards

  frontend:
    container_name: front_quizzcards
    image: snkhadim/quizzcards-frontend
    ports:
      - "80:80"
      #- "443:443"
    networks:
      - quizzcards
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    container_name: back_quizzcards
    image: snkhadim/quizzcards-backend
    ports:
      - "9000:9000"
    networks:
      - quizzcards
    depends_on:
      - database
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - IP_HOST=localhost
    restart: unless-stopped

networks:
  quizzcards:
    driver: bridge

volumes:
  mongo-data:
